spring:
  application:
    name: fieldsync-spring-api

  profiles:
    default: local

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      show-details: never